name: ecoloop
description: "EcoLoop - Smart Waste Management & Upcycling Platform"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  flutter_svg: ^2.2.0
  smooth_page_indicator: ^1.2.1

  # Animations
  animated_text_kit: ^4.2.3
  lottie: ^3.3.2

  # Networking & Data Storage
  dio: ^5.8.0
  retrofit: ^4.9.2
  json_annotation: ^4.12.0
  logger: ^2.6.0
  shared_preferences: ^2.5.5
  flutter_secure_storage: ^9.2.4

  dropdown_search: ^7.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Code Generators
  build_runner: ^2.4.15
  retrofit_generator: ^10.2.8
  json_serializable: ^6.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logo/